language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x

script:
  - go build ./...
  - go install github.com/golang/mock/mockgen
  - ./ci/check_go_fmt.sh
  - ./ci/check_go_generate.sh
  - go test -v ./...
