language: go

go:
  # go 1.4 is the first version to support "go generate"
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8

script:
  - go build ./...
  - go install github.com/golang/mock/mockgen
  - ./ci/check_go_fmt.sh
  - ./ci/check_go_generate.sh
  - go test -v ./...
